name: Release and sign the ComplyHub.dev Sigstore public key

on:
  push:
    paths:
      - cosign.pub
  workflow_dispatch:


permissions:
  contents: write

jobs:

  sign:
    name: Release and sign artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: sigstore/gh-action-sigstore-python@v2.1.0
        with:
          inputs: cosign.pub

      - name: Upload artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: cosign.pub.sigstore
          path: cosign.pub.sigstore

  release-github:
    needs: sign
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload release assets.
      contents: write
    steps:
      - name: Download artifacts directories # goes to current working directory
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          path: downloads/cosign.pub.sigstore

      - name: Upload artifacts to github
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          tag_name: latest
          files: |
            cosign.pub
            downloads/cosign.pub.sigstore
      
